# Site settings
title: Compilando.ES
description: .NET, Javascript, Sql Server y Azure por y para desarrolladores
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: rouge
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: compilando-es

# author info
# add your appropriate info here
author :
  name : Víctor Fernández Portero
  email : vfportero@gmail.com
  github : vfportero
  twitter : vfportero
bio:    # your bio
email: vfportero@gmail.com
email_md5: 3c0fdd7605ff0cd5fe6451f0a7e01ad8
twitter_username: vfportero
github_username: vfportero

# Theming options
# These settings are mandatory.
#theme:              'blue-pink'
theme: 'minima'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
